nginx:
  extends:
    file: common.yml
    service: nginx
  volumes:
    - ../app/static:/usr/share/nginx/html/static:ro
web:
  extends:
    file: common.yml
    service: web
  volumes:
   - ..:/code:ro
  environment:
    - NODE_PATH=/app/node_modules
  # entrypoint can't see volumes e.g. /code for some reason
  # for now clear out entrypoint and use command for development
  entrypoint: []
  command: /env/bin/python /code/main.py
  # command: /env/bin/uwsgi --py-autoreload=1 /code/uwsgi.ini
mysql:
  extends:
    file: common.yml
    service: mysql
