FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
# COPY static-html-directory /usr/share/nginx/html

COPY markhumphrey.io /etc/nginx/sites-available/markhumphrey.io
RUN mkdir /etc/nginx/sites-enabled/
RUN ln -s /etc/nginx/sites-available/markhumphrey.io /etc/nginx/sites-enabled/markhumphrey.io
