nginx:
  extends:
    file: common.yml
    service: nginx
web:
  extends:
    file: common.yml
    service: web
#  environment:
#    - REDIS_HOST=redis-production.example.com
mysql:
  extends:
    file: common.yml
    service: mysql
